"""updated instruments

Revision ID: 022ed4c685c8
Revises: 7b26c5047cea
Create Date: 2024-07-05 00:13:05.128878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022ed4c685c8'
down_revision = '7b26c5047cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('rent_price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('sale_price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('sale_price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('rent_price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
